### PR TITLE
17

### PR DESCRIPTION
**Pull request by scrizz**
@JSilvey these are the changes that will be merged.

### CODE REVIEW

**Comment by JSilvey** [comment]
This simple method is kicking my ass. I swear i have the logic down but it just isn't cooperating. I'll merge them and continue with what im doing. worse case scenario I just comment out my non working code. I've been working on this code since 2pm and no matter what i try it wont work (correctly).

**Comment by JSilvey** [comment]
Great job on the mute button! Its been driving me crazy with all the bug testing I've been doing.

**Comment by scrizz** [comment]
@JSilvey Try looking at some of the code for the Any search and see if that helps you.

EDIT: that's why I added the mute button lol. it was driving me crazy testing

**Comment by JSilvey** [comment]
I did. I started from scratch, then modified that code and its just not working. It may find the terms in one file but not in multiple. I have an hour to keep trying so hopefully something pops in my head. Its got to be something so small and stupid that I'm missing.

**Comment by scrizz** [comment]
@JSilvey is the code in your branch?

**Comment by JSilvey** [comment]
no, I'm just working main and just not commiting until it works

**Pull request merged**
